#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'poll_job'))
Delayed::Command.new(ARGV).daemonize
